// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjZCo4vwC4fJO6tBmOp85B3Ntjb7dpxPY',
    appId: '1:969160013809:web:b1ef55ef273d1ab4937650',
    messagingSenderId: '969160013809',
    projectId: 'flashcardsapp-56acc',
    authDomain: 'flashcardsapp-56acc.firebaseapp.com',
    storageBucket: 'flashcardsapp-56acc.firebasestorage.app',
    measurementId: 'G-V1YLLRN6WF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSVFgDN63XFTxM3cGXBVXbvSFilW054GM',
    appId: '1:969160013809:android:366b0fd84bfd18eb937650',
    messagingSenderId: '969160013809',
    projectId: 'flashcardsapp-56acc',
    storageBucket: 'flashcardsapp-56acc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpwS8mp7mLYrYmwjQVnpQMuA4kwyftu5E',
    appId: '1:969160013809:ios:af0c65e3cfb89f7f937650',
    messagingSenderId: '969160013809',
    projectId: 'flashcardsapp-56acc',
    storageBucket: 'flashcardsapp-56acc.firebasestorage.app',
    iosBundleId: 'com.example.flashcardsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpwS8mp7mLYrYmwjQVnpQMuA4kwyftu5E',
    appId: '1:969160013809:ios:af0c65e3cfb89f7f937650',
    messagingSenderId: '969160013809',
    projectId: 'flashcardsapp-56acc',
    storageBucket: 'flashcardsapp-56acc.firebasestorage.app',
    iosBundleId: 'com.example.flashcardsapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjZCo4vwC4fJO6tBmOp85B3Ntjb7dpxPY',
    appId: '1:969160013809:web:f1c8f76cadaaf9db937650',
    messagingSenderId: '969160013809',
    projectId: 'flashcardsapp-56acc',
    authDomain: 'flashcardsapp-56acc.firebaseapp.com',
    storageBucket: 'flashcardsapp-56acc.firebasestorage.app',
    measurementId: 'G-RTB1ECFX3W',
  );
}
